apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 # Cổng NodePort bạn muốn sử dụng (phải nằm trong khoảng từ 30000-32767)
  type: NodePort
